# Generated by Django 6.0.6 on 2026-06-22 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_systembackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('swap_type', models.CharField(choices=[('PROXY', "Proxy / Substitution (Teacher B takes Teacher A's class)"), ('MUTUAL', 'Mutual Time Swap (Exchange of class times)')], default='PROXY', max_length=10)),
                ('swap_date', models.DateField(help_text='The specific date for this temporary swap')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Requester')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for the swap request', null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('requester_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requester', to='academic.routineentry')),
                ('target_routine', models.ForeignKey(blank=True, help_text='Only required if swap_type is MUTUAL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_target', to='academic.routineentry')),
                ('target_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-swap_date', '-created_at'],
            },
        ),
    ]
