# Generated by Django 6.0.6 on 2026-07-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineentry',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='True if this class is pre-assigned by Admin'),
        ),
        migrations.CreateModel(
            name='FixedClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_schedules', to='academic.course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.day')),
                ('room', models.ForeignKey(blank=True, help_text='Optional: Fix a specific room too', null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.timeslot')),
            ],
            options={
                'ordering': ['day__order', 'time_slot__start_time'],
                'unique_together': {('day', 'time_slot', 'course')},
            },
        ),
    ]
