# Generated by Django 6.0.6 on 2026-07-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_routineentry_is_fixed_fixedclassschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fixed_day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fixed_time_slot',
        ),
        migrations.AlterField(
            model_name='course',
            name='fixed_room',
            field=models.ForeignKey(blank=True, help_text='Force the algorithm to always use this specific room for all classes of this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.room'),
        ),
        migrations.AlterUniqueTogether(
            name='routineentry',
            unique_together={('day', 'time_slot', 'course', 'group_name'), ('day', 'time_slot', 'room')},
        ),
    ]
