# Generated by Django 6.0.6 on 2026-07-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_course_fixed_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SWAP_REQ', 'Swap Request Received'), ('SWAP_ACC', 'Swap Request Accepted'), ('SWAP_REJ', 'Swap Request Rejected'), ('CLASS_DEL', 'Class Cancelled'), ('ADMIN_MSG', 'Admin Message'), ('NOTICE', 'System Notice')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft Delete: Uncheck to archive/hide this record instead of permanently deleting.')),
                ('notice_type', models.CharField(choices=[('GLOBAL', 'Global Notice (All Users)'), ('TARGETED', 'Targeted Notice (Specific Dept/Batch)')], default='TARGETED', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL)),
                ('target_batches', models.ManyToManyField(blank=True, related_name='notices', to='academic.batch')),
                ('target_departments', models.ManyToManyField(blank=True, related_name='notices', to='academic.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_notifications', to='academic.notice'),
        ),
    ]
