# Generated by Django 6.0.6 on 2026-07-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_notification_notification_type_notice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'department')},
        ),
    ]
