# Generated by Django 6.0.6 on 2026-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_batch_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel_bonus', models.IntegerField(default=50000, help_text='Bonus for scheduling parallel group classes. (Low: 1000 | Mid: 10000 | High: 50000+). The current value is intentionally very high to strongly prioritize parallel scheduling.')),
                ('edge_slot_penalty', models.IntegerField(default=2000, help_text='Penalty for assigning classes to the very first or last time slot of the day. (Low: 150 | Mid: 500 | High: 2000+). A higher value makes the algorithm avoid these slots unless necessary.')),
                ('zero_gap_bonus', models.IntegerField(default=1000, help_text='Bonus for schedules with no gaps between classes. (Low: 200 | Mid: 500 | High: 1000+).')),
                ('gap_penalty_per_slot', models.IntegerField(default=500, help_text='Penalty applied for each empty time slot (gap) between classes. (Low: 50 | Mid: 200 | High: 500+).')),
                ('center_gravity_bonus', models.IntegerField(default=50, help_text='Bonus for assigning classes to middle (comfort zone) time slots. (Low: 10 | Mid: 50 | High: 100+).')),
                ('continuous_class_penalty', models.IntegerField(default=100, help_text='Penalty for scheduling 3–4 consecutive classes without a break. (Low: 20 | Mid: 50 | High: 100+).')),
                ('day_load_penalty_multiplier', models.IntegerField(default=150, help_text='Penalty multiplier for overloading a single day with too many classes. (Low: 50 | Mid: 100 | High: 150+).')),
            ],
            options={
                'verbose_name': 'Algorithm Configuration',
                'verbose_name_plural': 'Algorithm Configuration',
            },
        ),
    ]
