# Generated by Django 6.0.6 on 2026-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_algorithmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='break_after_block_bonus',
            field=models.IntegerField(default=20000, help_text='Bonus for scheduling a break after a block of consecutive classes. (Low: 1000 | Mid: 5000 | High: 20000+). A higher value encourages the algorithm to insert breaks after long blocks of classes.'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='ideal_load_deviation_penalty',
            field=models.IntegerField(default=5000, help_text='Penalty for deviating from the ideal number of classes per day. (Low: 500 | Mid: 2000 | High: 5000+). A higher value encourages the algorithm to balance the number of classes across days.'),
        ),
    ]
