# Generated by Django 6.0.6 on 2026-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_algorithmconfig_break_after_block_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='lab_force_pair',
            field=models.BooleanField(default=True, help_text='True হলে ল্যাবের প্রতিটি সেশন জোড়া (2 স্লট একসাথে) হবে, False হলে প্রতি সেশন 1 স্লট হবে'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='lab_slots_per_credit',
            field=models.IntegerField(default=2, help_text='প্রতি ক্রেডিটে ল্যাবের জন্য কতটি স্লট বরাদ্দ হবে (ডিফল্ট: 2, অর্থাৎ 1 ক্রেডিট = 2 স্লট)'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='max_parallel_lab_groups',
            field=models.IntegerField(default=2, help_text='সর্বোচ্চ কতটি ল্যাব গ্রুপ একই সময়ে (একই স্লটে) সমান্তরালে চলতে পারবে'),
        ),
    ]
