# Generated by Django 6.0.6 on 2026-08-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_algorithmconfig_lab_force_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='load_balance_factor',
            field=models.IntegerField(default=20000, help_text='Daily load balancing factor. Bonus when load is below ideal, penalty when above. Higher value = stronger balancing.'),
        ),
        migrations.AlterField(
            model_name='algorithmconfig',
            name='lab_slots_per_credit',
            field=models.IntegerField(default=1, help_text='প্রতি ক্রেডিটে ল্যাবের জন্য কতটি স্লট বরাদ্দ হবে (ডিফল্ট: 1, অর্থাৎ 1 ক্রেডিট = 1 স্লট)'),
        ),
    ]
