# Generated by Django 6.0.6 on 2026-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_algorithmconfig_load_balance_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='adjacent_cluster_bonus',
            field=models.IntegerField(default=5000, help_text='Bonus when a class is placed immediately before or after an existing class of the same batch. (Low: 1000 | Mid: 5000 | High: 10000)'),
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='gap_square_penalty',
            field=models.IntegerField(default=800, help_text='Penalty multiplier for squared gap size. Larger gaps become extremely unattractive. (Low: 100 | Mid: 500 | High: 1000+)'),
        ),
    ]
